# examples:
#  allow: array
#  - { range: 127.0.0.1 }
#  - { scope: status, range: 127.0.0.1 }
#  - { scope: [apps, status], range: 127.0.0.1 }
# 
#   logging: object
#     { skip: true }
#     { scope: status, skip: true }
#     { scope: [apps, status], skip: true }
server:

  allow:
  - { range: 127.0.0.1 }

  logging:
    { scope: status, skip: true }

  app:
    module: '#module/where-server-app-server-information'

  auth: null

---
doc:

  allow:
  - { range: 127.0.0.1 }

  app:
    module: '#module/where-server-app-documents'

  auth: null
